name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.31'

      - name: Build and publish
        run: dotnet publish -c Release -o ./publish

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: myapp
          path: ./publish
